#!/usr/bin/env node
// Regenerates the three platform mirrors of failure-codes.json (FAILURES.md
// 4.2). Each mirror holds the codes whose `clients` include its platform, in
// registry order; the core mirror holds `core` OR `react-native`, because
// React Native re-exports core. The public names and shapes are the ones the
// call sites already use, so regenerating never changes a call site.
//
//   node scripts/gen-codes.mjs            write every mirror (takes contracts/.lock)
//   node scripts/gen-codes.mjs --check    exit 1 when a mirror differs from what
//                                         the registry generates (a hand edit)
//   --contracts-dir <dir>                 another contracts tree (tests); the SDK
//                                         root is its parent
//
// Never edit a mirror by hand. Add or change codes with scripts/add-code.mjs,
// which runs this generator while it holds the lock.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { CONTRACTS_DIR } from './lib/paths.mjs'
import { REGISTRY_FILE, readJson, validateRegistry, withLock, writeFileAtomic } from './lib/registry.mjs'

export const GENERATED_NOTE = 'Generated by contracts/scripts/gen-codes.mjs from failure-codes.json. Do not edit.'

// ── Text helpers ─────────────────────────────────────────────────────────────

/** Greedy word wrap: each line is `prefix` + words, at most `width` characters when a word allows it. */
export function wrap(text, prefix, width) {
  const lines = []
  let line = ''
  for (const word of text.split(/\s+/).filter(Boolean)) {
    const next = line ? `${line} ${word}` : word
    if (line && (prefix + next).length > width) {
      lines.push(prefix + line)
      line = word
    } else {
      line = next
    }
  }
  if (line) lines.push(prefix + line)
  return lines
}

/** `ad.audio_guard.exception` → `adAudioGuardException` (Swift names). */
export function camelName(code) {
  return code
    .split(/[._]/)
    .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join('')
}

/** `ad.audio_guard.exception` → `AD_AUDIO_GUARD_EXCEPTION` (Kotlin names). */
export function constName(code) {
  return code.toUpperCase().replace(/\./g, '_')
}

// ── Renderers ────────────────────────────────────────────────────────────────

function renderTs(entries) {
  const body = entries.map((e) => [
    '  /**',
    ...wrap(e.description, '   * ', 100),
    `   * Usually \`${e.component}\`, \`${e.severity}\`.`,
    '   */',
    `  '${e.code}',`,
  ].join('\n'))
  return `// ${GENERATED_NOTE}
//
// Failure codes the TS core and React Native report: the entries of
// contracts/failure-codes.json whose \`clients\` include \`core\` or
// \`react-native\` (React Native re-exports core), in registry order.
// test/failures-registry.test.ts checks this list against the JSON. To add a
// code, run contracts/scripts/add-code.mjs (contracts/FAILURES.md 4.4); it
// regenerates this file.
//
// Format: \`<area>.<operation>.<reason>\`. The registry's \`component\` and
// \`severity\` are what a call site usually passes; each call site decides.

export const FAILURE_CODES = [
${body.join('\n')}
] as const

/** A registry code this package may pass to logFailure. */
export type FailureCode = (typeof FAILURE_CODES)[number]
`
}

function renderSwift(entries) {
  const body = entries.map((e) => [
    ...wrap(e.description, '    /// ', 92),
    `    /// Usually \`${e.component}\`, \`${e.severity}\`.`,
    `    case ${camelName(e.code)} = "${e.code}"`,
  ].join('\n'))
  return `// ${GENERATED_NOTE}

import Foundation

/// Failure codes the iOS SDK reports: the entries of
/// contracts/failure-codes.json whose \`clients\` include \`ios\`, in registry
/// order. \`SellwildFailureCodeTests\` checks this list against the JSON. To
/// add a code, run contracts/scripts/add-code.mjs (contracts/FAILURES.md
/// 4.4); it regenerates this file.
///
/// Format: \`<area>.<operation>.<reason>\`. The registry's \`component\` and
/// \`severity\` are what a call site usually passes; each call site decides.
public enum SellwildFailureCode: String, CaseIterable {

${body.join('\n\n')}
}
`
}

function renderKotlin(entries) {
  const constants = entries.map((e) => `    /** ${e.description} */\n    const val ${constName(e.code)} = "${e.code}"`)
  const all = entries.map((e) => `        ${constName(e.code)},`)
  return `// ${GENERATED_NOTE}

package com.sellwild.sdk.failures

/**
 * Android mirror of contracts/failure-codes.json: every code whose \`clients\` include
 * \`android\` (FAILURES.md 4.2). FailureCodesParityTest checks this list against the JSON.
 *
 * To add a code, run contracts/scripts/add-code.mjs (FAILURES.md 4.4); it regenerates
 * this file.
 */
object SellwildFailureCode {
${constants.join('\n')}

    /** Every code above, in code order. */
    val ALL: List<String> = listOf(
${all.join('\n')}
    )
}

/** The \`component\` values logFailure accepts (FAILURES.md 6.2). Anything else becomes \`unknown\`. */
object SellwildFailureComponent {
    const val CONFIGURE = "configure"
    const val REMOTE_CONFIG = "remoteConfig"
    const val LISTINGS = "listings"
    const val LOCALIZED = "localized"
    const val FEED = "feed"
    const val BANNER = "banner"
    const val NATIVE = "native"
    const val VIDEO = "video"
    const val HOUSE = "house"
    const val BRIDGE = "bridge"
    const val WEBVIEW = "webview"
    const val WIDGET = "widget"
    const val GROWTHCODE = "growthcode"
    const val GEO = "geo"
    const val STORAGE = "storage"
}

/**
 * The \`severity\` values (FAILURES.md 6.3). logFailure defaults to [ERROR]; anything
 * else also becomes [ERROR].
 */
object SellwildFailureSeverity {
    /** The surface could not render. Sent at once, never sampled out. */
    const val FATAL = "fatal"

    /** The operation failed and a fallback was used. */
    const val ERROR = "error"

    /** Degraded but handled. */
    const val WARN = "warn"
}
`
}

/** The three mirrors: path from the SDK root, which clients it holds, and its renderer. */
export const MIRRORS = Object.freeze([
  { platform: 'core', path: 'core/src/failures/codes.ts', clients: ['core', 'react-native'], render: renderTs },
  { platform: 'ios', path: 'ios/Sources/SellwildSDK/Failures/SellwildFailureCode.swift', clients: ['ios'], render: renderSwift },
  { platform: 'android', path: 'android/src/main/kotlin/com/sellwild/sdk/failures/SellwildFailureCode.kt', clients: ['android'], render: renderKotlin },
])

/** The registry entries a mirror holds, in registry order. */
export function entriesFor(mirror, registry) {
  return registry.filter((e) => e.clients.some((c) => mirror.clients.includes(c)))
}

/** Every mirror's generated text: [{ mirror, file, text }]. Throws on an invalid registry. */
export function renderMirrors(registry, sdkRoot) {
  const errors = validateRegistry(registry)
  if (errors.length) throw new Error(`failure-codes.json is invalid:\n  ${errors.join('\n  ')}`)
  return MIRRORS.map((mirror) => ({
    mirror,
    file: path.join(sdkRoot, mirror.path),
    text: mirror.render(entriesFor(mirror, registry)),
  }))
}

/** Mirrors whose file differs from the generated text: [{ path, reason }]. */
export function staleMirrors(registry, sdkRoot) {
  const stale = []
  for (const { mirror, file, text } of renderMirrors(registry, sdkRoot)) {
    if (!fs.existsSync(file)) stale.push({ path: mirror.path, reason: 'missing' })
    else if (fs.readFileSync(file, 'utf8') !== text) stale.push({ path: mirror.path, reason: 'differs from the generated text' })
  }
  return stale
}

/**
 * Writes every mirror that changed. Returns the paths written. Caller holds the
 * lock. Temp files go in `contractsDir` (required), never next to the mirrors.
 */
export function writeMirrors(registry, sdkRoot, contractsDir) {
  if (typeof contractsDir !== 'string') throw new TypeError('writeMirrors needs the contracts dir for its temp files')
  const written = []
  for (const { mirror, file, text } of renderMirrors(registry, sdkRoot)) {
    if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === text) continue
    writeFileAtomic(file, text, contractsDir)
    written.push(mirror.path)
  }
  return written
}

// ── CLI ──────────────────────────────────────────────────────────────────────

function parseArgs(argv) {
  const args = { check: false, contractsDir: CONTRACTS_DIR }
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]
    if (a === '--check') args.check = true
    else if (a === '--contracts-dir' && i + 1 < argv.length) args.contractsDir = path.resolve(argv[++i])
    else if (a === '--contracts-dir') throw new Error('--contracts-dir needs a value')
    else throw new Error(`unknown argument ${a}`)
  }
  return args
}

export async function main(argv = process.argv.slice(2)) {
  const args = parseArgs(argv)
  const sdkRoot = path.dirname(args.contractsDir)
  const registryPath = path.join(args.contractsDir, REGISTRY_FILE)
  if (args.check) {
    const stale = staleMirrors(readJson(registryPath), sdkRoot)
    for (const s of stale) process.stderr.write(`stale mirror: ${s.path} (${s.reason}); run node contracts/scripts/gen-codes.mjs\n`)
    return stale.length ? 1 : 0
  }
  const written = await withLock(args.contractsDir, () => writeMirrors(readJson(registryPath), sdkRoot, args.contractsDir))
  process.stdout.write(written.length ? `wrote ${written.join(', ')}\n` : 'mirrors are up to date\n')
  return 0
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().then(
    (code) => { process.exitCode = code },
    (error) => {
      process.stderr.write(`gen-codes: ${error.message}\n`)
      process.exitCode = 1
    },
  )
}
