// Generated by contracts/scripts/gen-codes.mjs from failure-codes.json. Do not edit.

import Foundation

/// Failure codes the iOS SDK reports: the entries of
/// contracts/failure-codes.json whose `clients` include `ios`, in registry
/// order. `SellwildFailureCodeTests` checks this list against the JSON. To
/// add a code, run contracts/scripts/add-code.mjs (contracts/FAILURES.md
/// 4.4); it regenerates this file.
///
/// Format: `<area>.<operation>.<reason>`. The registry's `component` and
/// `severity` are what a call site usually passes; each call site decides.
public enum SellwildFailureCode: String, CaseIterable {

    /// The WebView mute shim (evaluateJavaScript) failed, so ad audio may not be muted.
    /// Usually `banner`, `warn`.
    case adAudioGuardException = "ad.audio_guard.exception"

    /// GAM failed to load an ad for a reason other than no-fill (network, invalid request,
    /// internal). No-fill stays on adError.
    /// Usually `banner`, `warn`.
    case adGamLoadException = "ad.gam_load.exception"

    /// No GAM ad unit is configured (gamTag and GAM both empty), so Google's test ad unit
    /// is used.
    /// Usually `banner`, `fatal`.
    case adGamUnitMissing = "ad.gam_unit.missing"

    /// Serializing imp.ext (gpid plus bidder params) failed, so no gpid is sent.
    /// Usually `banner`, `warn`.
    case adGpidException = "ad.gpid.exception"

    /// A native bid won but the cache id was missing or the native ad could not be created.
    /// No-fill stays on adError.
    /// Usually `native`, `error`.
    case adNativeCreateInvalid = "ad.native_create.invalid"

    /// A native ad image was rejected or failed to download.
    /// Usually `native`, `warn`.
    case adNativeImageNetwork = "ad.native_image.network"

    /// Serializing the global ORTB config failed, so app.publisher, device.geo and
    /// devicetype are missing.
    /// Usually `banner`, `warn`.
    case adOrtbConfigException = "ad.ortb_config.exception"

    /// A video creative won a banner-only zone (the existing placementMismatch event is
    /// also sent).
    /// Usually `banner`, `warn`.
    case adPlacementInvalid = "ad.placement.invalid"

    /// The Prebid auction returned an error result code other than no-bids (for example an
    /// invalid config id).
    /// Usually `banner`, `warn`.
    case adPrebidAuctionInvalid = "ad.prebid_auction.invalid"

    /// Prebid Mobile initialization threw or completed with an error, so every auction
    /// waits and may run without Prebid.
    /// Usually `banner`, `fatal`.
    case adPrebidInitException = "ad.prebid_init.exception"

    /// Prebid was not ready after the cold-start wait, so the ad loaded without header
    /// bidding.
    /// Usually `banner`, `warn`.
    case adPrebidInitTimeout = "ad.prebid_init.timeout"

    /// The Prebid rendering banner failed to load an ad for a reason other than no-fill.
    /// Usually `banner`, `warn`.
    case adPrebidRenderException = "ad.prebid_render.exception"

    /// No view controller was available to present the Prebid rendering banner.
    /// Usually `banner`, `warn`.
    case adPresenterMissing = "ad.presenter.missing"

    /// The ad view was created from a storyboard (init(coder:)), which is not supported.
    /// Usually `banner`, `fatal`.
    case adViewInitUnsupported = "ad.view_init.unsupported"

    /// An ad placement needs a zone id and none was given, so the auction is skipped.
    /// Usually `banner`, `error`.
    case adZoneMissing = "ad.zone.missing"

    /// Serializing the remote config across the React Native bridge failed, so bidder
    /// passthrough is lost.
    /// Usually `bridge`, `warn`.
    case bridgeConfigException = "bridge.config.exception"

    /// A config value from JS has the wrong type or is incomplete for the native bridge.
    /// Usually `bridge`, `fatal`.
    case bridgeConfigInvalid = "bridge.config.invalid"

    /// setExternalUserIds got an entry without source, uids or id; it was skipped.
    /// Usually `bridge`, `warn`.
    case bridgeEidsInvalid = "bridge.eids.invalid"

    /// setGeo got a payload it could not read: one that is not an object (geo was cleared)
    /// or a field of the wrong type (that field was dropped).
    /// Usually `bridge`, `warn`.
    case bridgeGeoInvalid = "bridge.geo.invalid"

    /// A WebView bridge message had a missing or wrong-typed field (type, url, listing,
    /// zoneId, message).
    /// Usually `bridge`, `warn`.
    case bridgeMessageInvalid = "bridge.message.invalid"

    /// A WebView bridge message was not valid JSON.
    /// Usually `bridge`, `warn`.
    case bridgeMessageParse = "bridge.message.parse"

    /// A WebView bridge message had an unknown type.
    /// Usually `bridge`, `warn`.
    case bridgeMessageUnsupported = "bridge.message.unsupported"

    /// A native view got missing props or an unsupported size label, so no ad was set up.
    /// Usually `bridge`, `error`.
    case bridgePropsInvalid = "bridge.props.invalid"

    /// The widget page reported a JavaScript error through the bridge ERROR message.
    /// Usually `webview`, `error`.
    case bridgeScriptException = "bridge.script.exception"

    /// Replacement action when a call site passes a code that fails the registry format.
    /// The label keeps the caller component. Never pass it directly.
    /// Usually `unknown`, `error`.
    case clientCodeInvalid = "client.code.invalid"

    /// APP_STORE_URL has no /id<number> segment, so app.bundle keeps the reverse-DNS
    /// default.
    /// Usually `configure`, `warn`.
    case configAppStoreUrlInvalid = "config.app_store_url.invalid"

    /// A BANNER_SIZES entry could not be parsed or has non-positive dimensions; it was
    /// dropped.
    /// Usually `remoteConfig`, `warn`.
    case configBannerSizesInvalid = "config.banner_sizes.invalid"

    /// The remote config request returned a non-2xx status (a missing file returns 403
    /// AccessDenied XML).
    /// Usually `remoteConfig`, `error`.
    case configFetchHttp = "config.fetch.http"

    /// The remote config request failed at the network level (DNS, offline, TLS, reset).
    /// Usually `remoteConfig`, `error`.
    case configFetchNetwork = "config.fetch.network"

    /// The remote config body is not valid JSON.
    /// Usually `remoteConfig`, `error`.
    case configFetchParse = "config.fetch.parse"

    /// The remote config request did not answer within the client timeout.
    /// Usually `remoteConfig`, `error`.
    case configFetchTimeout = "config.fetch.timeout"

    /// The remote config JSON is valid but not an object (array, string or null).
    /// Usually `remoteConfig`, `error`.
    case configParseInvalid = "config.parse.invalid"

    /// The stored remote config JSON could not be parsed, so every remote flag falls back
    /// to its default.
    /// Usually `remoteConfig`, `warn`.
    case configRemoteValuesParse = "config.remote_values.parse"

    /// The remote config URL could not be built from partnerCode and slug.
    /// Usually `configure`, `fatal`.
    case configUrlInvalid = "config.url.invalid"

    /// The COL1 layout asks for an ad or banner row but no zone is configured, so the row
    /// is dropped.
    /// Usually `feed`, `warn`.
    case feedAdZoneMissing = "feed.ad_zone.missing"

    /// A dequeued feed cell had an unexpected type.
    /// Usually `feed`, `fatal`.
    case feedCellInvalid = "feed.cell.invalid"

    /// A listing photo URL was rejected (scheme), too large, or could not be decoded.
    /// Usually `feed`, `warn`.
    case feedImageInvalid = "feed.image.invalid"

    /// A listing photo failed to download.
    /// Usually `feed`, `warn`.
    case feedImageNetwork = "feed.image.network"

    /// The COL1 layout contains an unknown token; it was ignored.
    /// Usually `feed`, `warn`.
    case feedLayoutInvalid = "feed.layout.invalid"

    /// A listing or partner URL was refused because it is not http(s).
    /// Usually `feed`, `warn`.
    case feedOpenUrlInvalid = "feed.open_url.invalid"

    /// GrowthCode is enabled but the partner id or sync URL is missing, so the sync cannot
    /// run.
    /// Usually `growthcode`, `warn`.
    case growthcodeConfigMissing = "growthcode.config.missing"

    /// The GrowthCode eid blob is not an array, or entries lack source/uids/id; they were
    /// dropped.
    /// Usually `growthcode`, `warn`.
    case growthcodeEidInvalid = "growthcode.eid.invalid"

    /// The GrowthCode sync returned a non-2xx status; the throttle is not saved, so it
    /// retries next launch.
    /// Usually `growthcode`, `warn`.
    case growthcodeSyncHttp = "growthcode.sync.http"

    /// The GrowthCode sync request failed at the network level.
    /// Usually `growthcode`, `warn`.
    case growthcodeSyncNetwork = "growthcode.sync.network"

    /// The GrowthCode sync response is not valid JSON.
    /// Usually `growthcode`, `warn`.
    case growthcodeSyncParse = "growthcode.sync.parse"

    /// GrowthCode sync POST timed out. The throttle is not persisted, so it retries next
    /// launch.
    /// Usually `growthcode`, `warn`.
    case growthcodeSyncTimeout = "growthcode.sync.timeout"

    /// The GrowthCode endpoint URL could not be built.
    /// Usually `growthcode`, `warn`.
    case growthcodeUrlInvalid = "growthcode.url.invalid"

    /// A house ad image was rejected (scheme), too large, or could not be decoded.
    /// Usually `house`, `warn`.
    case houseImageInvalid = "house.image.invalid"

    /// A house ad image failed to download.
    /// Usually `house`, `warn`.
    case houseImageNetwork = "house.image.network"

    /// A house ad click URL was refused because it is not http(s).
    /// Usually `house`, `warn`.
    case houseOpenUrlInvalid = "house.open_url.invalid"

    /// The listings client was released or disposed while a request was in flight.
    /// Usually `listings`, `warn`.
    case listingsClientMissing = "listings.client.missing"

    /// The listings GET returned a non-2xx status.
    /// Usually `listings`, `error`.
    case listingsFetchHttp = "listings.fetch.http"

    /// The listings request finished without a body.
    /// Usually `listings`, `error`.
    case listingsFetchMissing = "listings.fetch.missing"

    /// The listings GET failed at the network level (DNS, offline, TLS, reset).
    /// Usually `listings`, `error`.
    case listingsFetchNetwork = "listings.fetch.network"

    /// The listings body is not valid JSON (for example an HTML error page).
    /// Usually `listings`, `error`.
    case listingsFetchParse = "listings.fetch.parse"

    /// Listings GET did not answer within the client timeout.
    /// Usually `listings`, `error`.
    case listingsFetchTimeout = "listings.fetch.timeout"

    /// Decoding a listing item threw (strict casts on real payloads).
    /// Usually `listings`, `error`.
    case listingsItemParse = "listings.item.parse"

    /// The listings JSON is valid but has no result.rs array.
    /// Usually `listings`, `error`.
    case listingsParseInvalid = "listings.parse.invalid"

    /// Encoding the JSON-RPC listings request failed.
    /// Usually `listings`, `error`.
    case listingsRequestException = "listings.request.exception"

    /// The listings URL is not a valid URL.
    /// Usually `listings`, `error`.
    case listingsUrlInvalid = "listings.url.invalid"

    /// LOCALIZED_LISTINGS is set but not an object, or lacks baseUrl/urlTemplate; the
    /// feature is off.
    /// Usually `localized`, `warn`.
    case localizedConfigInvalid = "localized.config.invalid"

    /// The localized cache returned a non-2xx status other than the expected 403/404 for a
    /// state without a cache.
    /// Usually `localized`, `warn`.
    case localizedFetchHttp = "localized.fetch.http"

    /// The localized cache request finished without a body.
    /// Usually `localized`, `warn`.
    case localizedFetchMissing = "localized.fetch.missing"

    /// The localized (per-state) cache request failed at the network level.
    /// Usually `localized`, `warn`.
    case localizedFetchNetwork = "localized.fetch.network"

    /// The localized cache body is not valid JSON.
    /// Usually `localized`, `warn`.
    case localizedFetchParse = "localized.fetch.parse"

    /// Localized (per-state) listings cache GET timed out. The primary feed renders alone.
    /// Usually `localized`, `warn`.
    case localizedFetchTimeout = "localized.fetch.timeout"

    /// The localized cache URL could not be built from baseUrl and urlTemplate.
    /// Usually `localized`, `warn`.
    case localizedUrlInvalid = "localized.url.invalid"

    /// Creating the on-disk cache directory failed.
    /// Usually `storage`, `warn`.
    case storageCacheDirException = "storage.cache_dir.exception"

    /// Writing a stored value (localStorage, disk cache) failed.
    /// Usually `storage`, `warn`.
    case storageWriteException = "storage.write.exception"

    /// Serializing a remote config value into a widget attribute failed; the attribute was
    /// left out.
    /// Usually `webview`, `warn`.
    case widgetAttributesException = "widget.attributes.exception"

    /// The widget WebView got an HTTP error status (4xx or 5xx) for its page or a
    /// main-frame resource.
    /// Usually `webview`, `error`.
    case widgetWebviewLoadHttp = "widget.webview_load.http"

    /// The widget WebView failed to load its page or a main resource (offline, DNS, TLS,
    /// navigation failure).
    /// Usually `webview`, `error`.
    case widgetWebviewLoadNetwork = "widget.webview_load.network"

    /// The WebView content process crashed or was killed (iOS
    /// webViewWebContentProcessDidTerminate, Android onRenderProcessGone). The widget is
    /// blank until reloaded.
    /// Usually `webview`, `error`.
    case widgetWebviewProcessException = "widget.webview_process.exception"
}
